version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./stacks:/srv               # Carpeta para tus archivos
      - ./filebrowser.db:/database.db # Archivo de base de datos
      - ./settings.json:/settings.json # Archivo de configuración
    environment:
      UID: 1000                      # Establecer UID
      GID: 1000                      # Establecer GID
    ports:
      - "5040:5040"                  # Exponer puerto 5040 dentro del contenedor y del host
    user: "${UID}:${GID}"            # Usar UID y GID del sistema para permisos adecuados
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"                    # Puerto HTTP
      - "8443:443"                   # Puerto HTTPS
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Archivo de configuración de NGINX
      - ./.nginx/ssl:/etc/nginx/ssl   # Carpeta con certificados SSL (si los usas)
    networks:
      - webnet
    depends_on:
      - filebrowser
    environment:
      - NGINX_HOST=localhost

networks:
  webnet:
    driver: bridge
