version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./stacks:/srv                # Carpeta para archivos
      - ./filebrowser.db:/config/database.db  # Ajustada la ruta
      - ./.filebrowser.json:/config/.filebrowser.json
    environment:
      UID: 1000                      # Establecer UID
      GID: 1000                      # Establecer GID
    ports:
      - "5040:8080"
    user: "1000:1000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/ssl:/etc/nginx/ssl
    networks:
      - webnet
    depends_on:
      - filebrowser

networks:
  webnet:
    driver: bridge
