version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./stacks:/srv               # Carpeta para tus archivos
      - ./filebrowser.db:/database.db # Archivo de base de datos
      - ./settings.json:/settings.json # Archivo de configuración
    environment:
      PUID: ${UID:-1000}             # PUID configurado por variable de entorno (si no, por defecto 1000)
      PGID: ${GID:-1000}             # PGID configurado por variable de entorno (si no, por defecto 1000)
    ports:
      - "5040:5040"                  # Exponer puerto 5040 dentro del contenedor y del host
    user: "${UID}:${GID}"            # Usar UID y GID del sistema para permisos adecuados
    networks:
      - webnet                       # Asegúrate de que filebrowser esté en la misma red

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"                    # Puerto HTTP
      - "8443:443"                   # Puerto HTTPS
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Archivo de configuración de NGINX
      - ./.nginx/ssl:/etc/nginx/ssl   # Carpeta con certificados SSL (si los usas)
    networks:
      - webnet                       # Asegúrate de que nginx esté en la misma red
    depends_on:
      - filebrowser                   # NGINX depende de filebrowser
    environment:
      - NGINX_HOST=localhost          # Puedes agregar configuraciones de entorno si las necesitas

networks:
  webnet:
    driver: bridge                   # Usamos el driver 'bridge' para la red compartida
